#!/usr/bin/env bash
# Generate docs/DOCS_INDEX.md from design doc frontmatter.
#
# Usage: bash scripts/generate-docs-index.sh
#
# Extracts YAML frontmatter from all docs/design/**/*.md and produces
# a compact markdown table for AI session context injection.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
DESIGN_DIR="$REPO_ROOT/docs/design"
OUTPUT="$REPO_ROOT/docs/DOCS_INDEX.md"

if [[ ! -d "$DESIGN_DIR" ]]; then
  echo "No design docs directory at $DESIGN_DIR — skipping"
  exit 0
fi

# Extract a frontmatter field value from between --- markers
get_field() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//;s/"$//' | tr -d '\r' || true
}

# Collect all design docs
ENTRIES=""
COUNT=0
MISSING=0
SKIPPED=0

while IFS= read -r filepath; do
  title=$(get_field "$filepath" "title")
  if [[ -z "$title" ]]; then
    MISSING=$((MISSING + 1))
    echo "WARNING: missing frontmatter: ${filepath#"$REPO_ROOT"/}" >&2
    continue
  fi

  status=$(get_field "$filepath" "status")

  # Skip superseded docs — their guidance is replaced by another doc
  if [[ "$status" == "superseded" ]]; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  description=$(get_field "$filepath" "description")
  relpath="${filepath#"$REPO_ROOT"/}"

  ENTRIES="${ENTRIES}| ${title} | ${description} | ${status} | ${relpath} |
"
  COUNT=$((COUNT + 1))
done < <(find "$DESIGN_DIR" -name '*.md' -type f | sort)

if [[ $COUNT -eq 0 ]]; then
  echo "No design docs with frontmatter found — skipping"
  exit 0
fi

# Generate the index
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
# Design Document Index

> Auto-generated by ship plugin (scripts/generate-docs-index.sh). Do not edit manually.

| Name | Description | Status | Path |
|------|-------------|--------|------|
${ENTRIES}
EOF

echo "Generated $OUTPUT with $COUNT entries"
[[ $SKIPPED -gt 0 ]] && echo "Skipped $SKIPPED superseded doc(s)"
[[ $MISSING -gt 0 ]] && echo "WARNING: $MISSING doc(s) missing frontmatter (not included)"
