#!/usr/bin/env python3
"""Generate docs/DESIGN_INDEX.md from design doc frontmatter.

Usage: python3 scripts/generate-design-index.py

This extracts YAML frontmatter from all design docs and produces a
compact markdown table that can be injected into AI session context.
"""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DESIGN_DIR = REPO_ROOT / "docs" / "design"
OUTPUT = REPO_ROOT / "docs" / "DESIGN_INDEX.md"


def extract_frontmatter(filepath: Path) -> dict | None:
    """Extract YAML frontmatter fields from a markdown file."""
    content = filepath.read_text(encoding="utf-8")
    if not content.startswith("---"):
        return None

    parts = content.split("---", 2)
    if len(parts) < 3:
        return None

    fm = parts[1]
    fields = {}
    for key in ("title", "description", "number", "status", "superseded_by", "services"):
        match = re.search(rf'^{key}:\s*"?(.+?)"?\s*$', fm, re.MULTILINE)
        if match:
            val = match.group(1).strip().strip('"')
            fields[key] = val

    # Parse services as list
    svc_match = re.search(r"^services:\s*\[(.+?)\]", fm, re.MULTILINE)
    if svc_match:
        fields["services"] = svc_match.group(1).strip()

    # Parse related as list
    rel_match = re.search(r'^related:\s*\[(.+?)\]', fm, re.MULTILINE)
    if rel_match:
        fields["related"] = rel_match.group(1).strip().replace('"', '')

    return fields if fields.get("number") else None


def collect_docs() -> list[dict]:
    """Collect frontmatter from all design docs.

    Auto-discovers all .md files under docs/design/ recursively,
    so new subdirectories are picked up without script changes.
    """
    docs = []
    missing = []
    seen = set()
    for filepath in sorted(DESIGN_DIR.rglob("*.md")):
        fp = Path(filepath)
        if fp in seen:
            continue
        seen.add(fp)
        fm = extract_frontmatter(fp)
        if fm:
            fm["path"] = str(fp.relative_to(REPO_ROOT))
            docs.append(fm)
        else:
            missing.append(str(fp.relative_to(REPO_ROOT)))

    if missing:
        print(f"WARNING: {len(missing)} doc(s) missing frontmatter (not included in index):")
        for m in missing:
            print(f"  - {m}")

    return docs


def sort_key(doc: dict) -> tuple:
    """Sort: agents/ last, then by number."""
    num = doc.get("number", "999")
    is_agent = num.startswith("agents/")
    sort_num = num.replace("agents/", "")
    try:
        return (is_agent, int(sort_num))
    except ValueError:
        return (is_agent, 999)


STATUS_EMOJI = {
    "current": "✅",
    "partially-outdated": "⚠️",
    "superseded": "🚫",
    "draft": "📝",
    "not-implemented": "🔲",
}


def generate_index(docs: list[dict]) -> str:
    """Generate the markdown index."""
    lines = [
        "# Design Document Index",
        "",
        "> Auto-generated by `scripts/generate-design-index.py`. Do not edit manually.",
        "> Re-generate: `python3 scripts/generate-design-index.py`",
        "",
        "| # | St | Services | Description |",
        "|---|---|----------|-------------|",
    ]

    for doc in sorted(docs, key=sort_key):
        num = doc.get("number", "?")
        status = doc.get("status", "?")
        emoji = STATUS_EMOJI.get(status, "❓")
        services = doc.get("services", "")
        desc = doc.get("description", doc.get("title", ""))
        sup = doc.get("superseded_by", "")
        if sup:
            desc += f" → {sup}"

        lines.append(f"| {num} | {emoji} | {services} | {desc} |")

    lines.append("")
    lines.append("**Legend:** ✅ current · ⚠️ partially-outdated · 🚫 superseded · 📝 draft · 🔲 not-implemented")
    lines.append("")
    return "\n".join(lines)


def main():
    if not DESIGN_DIR.exists():
        print(f"No design docs directory at {DESIGN_DIR} — skipping")
        return

    docs = collect_docs()
    if not docs:
        print("No design docs with frontmatter found — skipping")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    index = generate_index(docs)
    OUTPUT.write_text(index, encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(docs)} entries")


if __name__ == "__main__":
    main()
